import type { Books, Location, Movement, StockLine, Wine, WineColor } from "./types"

type Bin = {
  locationId: string
  cases: number
  loose?: number
  allocatedCases?: number
  allocatedLoose?: number
}

type Draft = {
  id: string
  sku: string
  producer: string
  cuvee: string
  vintage: number | null
  color: WineColor
  varietal: string
  country: string
  region: string
  appellation: string
  abv: number
  cost: number
  price: number
  reorder: number
  supplier: string
  pack?: number
  active?: boolean
  note?: string
  bins: Bin[]
}

const locations: Location[] = [
  {
    id: "oak",
    name: "Oakland Bonded",
    city: "Oakland",
    kind: "bonded",
    capacityCases: 2400,
  },
  {
    id: "napa",
    name: "Napa Cold Room",
    city: "Napa",
    kind: "cold",
    capacityCases: 480,
  },
  {
    id: "sf",
    name: "Fillmore Will-Call",
    city: "San Francisco",
    kind: "will-call",
    capacityCases: 160,
  },
]

const drafts: Draft[] = [
  {
    id: "w-charmes",
    sku: "MAR-CHA-22",
    producer: "Domaine Marchand",
    cuvee: "Les Charmes",
    vintage: 2022,
    color: "red",
    varietal: "Pinot Noir",
    country: "France",
    region: "Burgundy",
    appellation: "Chambolle-Musigny",
    abv: 13,
    cost: 468,
    price: 690,
    reorder: 6,
    supplier: "Domaine Marchand",
    note: "Village-level demand from the Oakland list. Keep a full pallet when the next allocation lands.",
    bins: [
      { locationId: "oak", cases: 18, allocatedCases: 6 },
      { locationId: "napa", cases: 4 },
      { locationId: "sf", cases: 2 },
    ],
  },
  {
    id: "w-bourgogne",
    sku: "MAR-BOU-23",
    producer: "Domaine Marchand",
    cuvee: "Bourgogne Rouge",
    vintage: 2023,
    color: "red",
    varietal: "Pinot Noir",
    country: "France",
    region: "Burgundy",
    appellation: "Bourgogne",
    abv: 12.5,
    cost: 168,
    price: 252,
    reorder: 15,
    supplier: "Domaine Marchand",
    bins: [
      { locationId: "oak", cases: 46, allocatedCases: 8 },
      { locationId: "sf", cases: 6 },
    ],
  },
  {
    id: "w-vaillons",
    sku: "ELO-VAI-22",
    producer: "Maison Elodie",
    cuvee: "Vaillons",
    vintage: 2022,
    color: "white",
    varietal: "Chardonnay",
    country: "France",
    region: "Burgundy",
    appellation: "Chablis 1er Cru",
    abv: 13,
    cost: 312,
    price: 468,
    reorder: 8,
    supplier: "Maison Elodie",
    bins: [
      { locationId: "oak", cases: 14, allocatedCases: 4 },
      { locationId: "napa", cases: 10 },
    ],
  },
  {
    id: "w-petit-chablis",
    sku: "ELO-PET-24",
    producer: "Maison Elodie",
    cuvee: "Petit Chablis",
    vintage: 2024,
    color: "white",
    varietal: "Chardonnay",
    country: "France",
    region: "Burgundy",
    appellation: "Petit Chablis",
    abv: 12,
    cost: 126,
    price: 198,
    reorder: 20,
    supplier: "Maison Elodie",
    note: "By-the-glass pour at three accounts. The next container is still on the water.",
    bins: [
      { locationId: "oak", cases: 8 },
      { locationId: "napa", cases: 6 },
    ],
  },
  {
    id: "w-st-emilion",
    sku: "LAC-STE-19",
    producer: "Château Lacombe",
    cuvee: "Saint-Émilion Grand Cru",
    vintage: 2019,
    color: "red",
    varietal: "Merlot, Cabernet Franc",
    country: "France",
    region: "Bordeaux",
    appellation: "Saint-Émilion Grand Cru",
    abv: 14,
    cost: 540,
    price: 840,
    reorder: 4,
    supplier: "Château Lacombe",
    note: "Nine cases at Oakland are already spoken for. Sell the free cases one at a time.",
    bins: [
      { locationId: "oak", cases: 11, allocatedCases: 9 },
      { locationId: "sf", cases: 1 },
    ],
  },
  {
    id: "w-bx-sup",
    sku: "LAC-SUP-22",
    producer: "Château Lacombe",
    cuvee: "Bordeaux Supérieur",
    vintage: 2022,
    color: "red",
    varietal: "Merlot, Cabernet Sauvignon",
    country: "France",
    region: "Bordeaux",
    appellation: "Bordeaux Supérieur",
    abv: 13.5,
    cost: 96,
    price: 156,
    reorder: 24,
    supplier: "Château Lacombe",
    bins: [
      { locationId: "oak", cases: 62, allocatedCases: 10 },
      { locationId: "sf", cases: 8 },
    ],
  },
  {
    id: "w-wv-pinot",
    sku: "HEA-WIL-23",
    producer: "Hearth Hill",
    cuvee: "Willamette Valley",
    vintage: 2023,
    color: "red",
    varietal: "Pinot Noir",
    country: "United States",
    region: "Oregon",
    appellation: "Willamette Valley",
    abv: 13.5,
    cost: 216,
    price: 336,
    reorder: 12,
    supplier: "Hearth Hill",
    bins: [
      { locationId: "oak", cases: 22 },
      { locationId: "sf", cases: 4, allocatedCases: 2 },
    ],
  },
  {
    id: "w-dundee",
    sku: "HEA-DUN-22",
    producer: "Hearth Hill",
    cuvee: "Dundee Hills",
    vintage: 2022,
    color: "red",
    varietal: "Pinot Noir",
    country: "United States",
    region: "Oregon",
    appellation: "Dundee Hills",
    abv: 13.5,
    cost: 288,
    price: 444,
    reorder: 6,
    supplier: "Hearth Hill",
    bins: [
      { locationId: "oak", cases: 9, allocatedCases: 3 },
      { locationId: "napa", cases: 2 },
    ],
  },
  {
    id: "w-sonoma-chard",
    sku: "SAL-SON-23",
    producer: "Salt & Cedar",
    cuvee: "Sonoma Coast",
    vintage: 2023,
    color: "white",
    varietal: "Chardonnay",
    country: "United States",
    region: "California",
    appellation: "Sonoma Coast",
    abv: 13.2,
    cost: 192,
    price: 300,
    reorder: 10,
    supplier: "Salt & Cedar",
    bins: [
      { locationId: "napa", cases: 16 },
      { locationId: "oak", cases: 7, allocatedCases: 4 },
      { locationId: "sf", cases: 3 },
    ],
  },
  {
    id: "w-rr-pinot",
    sku: "SAL-RUS-22",
    producer: "Salt & Cedar",
    cuvee: "Russian River Valley",
    vintage: 2022,
    color: "red",
    varietal: "Pinot Noir",
    country: "United States",
    region: "California",
    appellation: "Russian River Valley",
    abv: 14,
    cost: 240,
    price: 372,
    reorder: 8,
    supplier: "Salt & Cedar",
    bins: [
      { locationId: "oak", cases: 13, allocatedCases: 5 },
      { locationId: "sf", cases: 2, loose: 1 },
    ],
  },
  {
    id: "w-barolo",
    sku: "VER-BAR-19",
    producer: "Cantina Vero",
    cuvee: "Barolo",
    vintage: 2019,
    color: "red",
    varietal: "Nebbiolo",
    country: "Italy",
    region: "Piedmont",
    appellation: "Barolo",
    abv: 14.5,
    cost: 420,
    price: 660,
    reorder: 5,
    supplier: "Cantina Vero",
    bins: [{ locationId: "oak", cases: 7, allocatedCases: 2 }],
  },
  {
    id: "w-langhe",
    sku: "VER-LAN-22",
    producer: "Cantina Vero",
    cuvee: "Langhe Nebbiolo",
    vintage: 2022,
    color: "red",
    varietal: "Nebbiolo",
    country: "Italy",
    region: "Piedmont",
    appellation: "Langhe",
    abv: 14,
    cost: 144,
    price: 228,
    reorder: 10,
    supplier: "Cantina Vero",
    note: "The fall by-the-glass placements outran the last receipt.",
    bins: [
      { locationId: "oak", cases: 4 },
      { locationId: "sf", cases: 1 },
    ],
  },
  {
    id: "w-reserva",
    sku: "SOL-RES-18",
    producer: "Bodega Solana",
    cuvee: "Reserva",
    vintage: 2018,
    color: "red",
    varietal: "Tempranillo",
    country: "Spain",
    region: "Rioja",
    appellation: "Rioja Alta",
    abv: 14,
    cost: 156,
    price: 246,
    reorder: 12,
    supplier: "Bodega Solana",
    bins: [
      { locationId: "oak", cases: 28, allocatedCases: 6 },
      { locationId: "sf", cases: 5 },
    ],
  },
  {
    id: "w-crianza",
    sku: "SOL-CRI-21",
    producer: "Bodega Solana",
    cuvee: "Crianza",
    vintage: 2021,
    color: "red",
    varietal: "Tempranillo",
    country: "Spain",
    region: "Rioja",
    appellation: "Rioja",
    abv: 13.5,
    cost: 108,
    price: 174,
    reorder: 18,
    supplier: "Bodega Solana",
    bins: [
      { locationId: "oak", cases: 11 },
      { locationId: "sf", cases: 3 },
    ],
  },
  {
    id: "w-sancerre",
    sku: "RIV-SAN-24",
    producer: "Clos du Rivage",
    cuvee: "Sancerre",
    vintage: 2024,
    color: "white",
    varietal: "Sauvignon Blanc",
    country: "France",
    region: "Loire",
    appellation: "Sancerre",
    abv: 13,
    cost: 180,
    price: 276,
    reorder: 14,
    supplier: "Clos du Rivage",
    bins: [
      { locationId: "napa", cases: 20 },
      { locationId: "oak", cases: 6, allocatedCases: 4 },
      { locationId: "sf", cases: 4 },
    ],
  },
  {
    id: "w-rose",
    sku: "RIV-ROS-24",
    producer: "Clos du Rivage",
    cuvee: "Rosé de Loire",
    vintage: 2024,
    color: "rose",
    varietal: "Gamay, Grolleau",
    country: "France",
    region: "Loire",
    appellation: "Rosé de Loire",
    abv: 12.5,
    cost: 114,
    price: 180,
    reorder: 16,
    supplier: "Clos du Rivage",
    note: "Summer pours are winding down. Buy again in March.",
    bins: [
      { locationId: "oak", cases: 9 },
      { locationId: "sf", cases: 2 },
    ],
  },
  {
    id: "w-brut",
    sku: "PEL-BRU-NV",
    producer: "House of Pellier",
    cuvee: "Brut Réserve",
    vintage: null,
    color: "sparkling",
    varietal: "Pinot Noir, Chardonnay, Pinot Meunier",
    country: "France",
    region: "Champagne",
    appellation: "Champagne",
    abv: 12,
    cost: 264,
    price: 420,
    reorder: 10,
    supplier: "House of Pellier",
    pack: 6,
    note: "Holiday lists go out next month. The house is short.",
    bins: [
      { locationId: "oak", cases: 3 },
      { locationId: "sf", cases: 1, allocatedCases: 1 },
    ],
  },
  {
    id: "w-bdb",
    sku: "PEL-BDB-18",
    producer: "House of Pellier",
    cuvee: "Blanc de Blancs",
    vintage: 2018,
    color: "sparkling",
    varietal: "Chardonnay",
    country: "France",
    region: "Champagne",
    appellation: "Champagne",
    abv: 12,
    cost: 390,
    price: 612,
    reorder: 4,
    supplier: "House of Pellier",
    pack: 6,
    bins: [
      { locationId: "oak", cases: 5, allocatedCases: 2 },
      { locationId: "napa", cases: 2 },
    ],
  },
  {
    id: "w-tawny",
    sku: "LAP-TAW-NV",
    producer: "Quinta da Lapa",
    cuvee: "10 Year Tawny",
    vintage: null,
    color: "fortified",
    varietal: "Tinta Roriz, Tinta Barroca, Touriga Nacional",
    country: "Portugal",
    region: "Douro",
    appellation: "Porto",
    abv: 20,
    cost: 198,
    price: 312,
    reorder: 4,
    supplier: "Quinta da Lapa",
    pack: 6,
    note: "The last bottles went to the staff tasting. Place the reorder with the quinta.",
    bins: [{ locationId: "oak", cases: 0 }],
  },
  {
    id: "w-etna",
    sku: "ALT-ETN-22",
    producer: "Vigna Alta",
    cuvee: "Etna Rosso",
    vintage: 2022,
    color: "red",
    varietal: "Nerello Mascalese",
    country: "Italy",
    region: "Sicily",
    appellation: "Etna",
    abv: 13.5,
    cost: 174,
    price: 270,
    reorder: 6,
    supplier: "Vigna Alta",
    bins: [
      { locationId: "oak", cases: 12, allocatedCases: 2 },
      { locationId: "sf", cases: 2 },
    ],
  },
  {
    id: "w-sauv-blanc",
    sku: "COO-SAU-25",
    producer: "Cooper's Bench",
    cuvee: "Marlborough",
    vintage: 2025,
    color: "white",
    varietal: "Sauvignon Blanc",
    country: "New Zealand",
    region: "Marlborough",
    appellation: "Marlborough",
    abv: 13,
    cost: 102,
    price: 168,
    reorder: 30,
    supplier: "Cooper's Bench",
    note: "Fresh receipt. Cold room takes the bulk; Fillmore keeps a will-call stack.",
    bins: [
      { locationId: "oak", cases: 40 },
      { locationId: "napa", cases: 24 },
      { locationId: "sf", cases: 8 },
    ],
  },
  {
    id: "w-cab",
    sku: "BLA-CAB-21",
    producer: "Blackthorn",
    cuvee: "Napa Valley",
    vintage: 2021,
    color: "red",
    varietal: "Cabernet Sauvignon",
    country: "United States",
    region: "California",
    appellation: "Napa Valley",
    abv: 14.5,
    cost: 360,
    price: 540,
    reorder: 8,
    supplier: "Blackthorn",
    note: "Valley Provisions is holding four cases for the November list.",
    bins: [
      { locationId: "oak", cases: 5, allocatedCases: 4 },
      { locationId: "sf", cases: 1 },
    ],
  },
  {
    id: "w-chablis-20",
    sku: "ELO-CHB-20",
    producer: "Maison Elodie",
    cuvee: "Chablis",
    vintage: 2020,
    color: "white",
    varietal: "Chardonnay",
    country: "France",
    region: "Burgundy",
    appellation: "Chablis",
    abv: 12.5,
    cost: 168,
    price: 246,
    reorder: 0,
    supplier: "Maison Elodie",
    active: false,
    note: "Vintage closed. Sell the last two cases.",
    bins: [{ locationId: "oak", cases: 2 }],
  },
]

function hoursAgo(now: Date, hours: number) {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString()
}

function movement(
  now: Date,
  hours: number,
  partial: Omit<Movement, "id" | "at" | "account" | "note"> & {
    account?: string
    note?: string
  },
): Movement {
  return {
    account: "",
    note: "",
    ...partial,
    id: `m-${hours}`,
    at: hoursAgo(now, hours),
  }
}

export function seedBooks(now = new Date()): Books {
  const wines: Wine[] = []
  const stock: StockLine[] = []

  for (const draft of drafts) {
    const pack = draft.pack ?? 12
    wines.push({
      id: draft.id,
      sku: draft.sku,
      producer: draft.producer,
      cuvee: draft.cuvee,
      vintage: draft.vintage,
      color: draft.color,
      varietal: draft.varietal,
      country: draft.country,
      region: draft.region,
      appellation: draft.appellation,
      formatMl: 750,
      bottlesPerCase: pack,
      abv: draft.abv,
      costPerCase: draft.cost,
      pricePerCase: draft.price,
      reorderCases: draft.reorder,
      supplier: draft.supplier,
      active: draft.active ?? true,
      note: draft.note ?? "",
    })
    for (const bin of draft.bins) {
      stock.push({
        wineId: draft.id,
        locationId: bin.locationId,
        onHandBottles: bin.cases * pack + (bin.loose ?? 0),
        allocatedBottles: (bin.allocatedCases ?? 0) * pack + (bin.allocatedLoose ?? 0),
      })
    }
  }

  const movements: Movement[] = [
    movement(now, 2, {
      type: "receive",
      wineId: "w-sauv-blanc",
      locationId: "oak",
      bottles: 40 * 12,
      reference: "PO-4481",
      note: "Container floor count, Oakland dock",
    }),
    movement(now, 5, {
      type: "ship",
      wineId: "w-bourgogne",
      locationId: "oak",
      bottles: 4 * 12,
      reference: "INV-9102",
      account: "Chez Lumen",
    }),
    movement(now, 20, {
      type: "allocate",
      wineId: "w-brut",
      locationId: "sf",
      bottles: 1 * 6,
      reference: "HOLD-338",
      account: "Bar Clementine",
      note: "Saturday service",
    }),
    movement(now, 26, {
      type: "ship",
      wineId: "w-sonoma-chard",
      locationId: "oak",
      bottles: 3 * 12,
      reference: "INV-9108",
      account: "The Harbor Room",
    }),
    movement(now, 30, {
      type: "transfer",
      wineId: "w-sancerre",
      locationId: "oak",
      toLocationId: "napa",
      bottles: 6 * 12,
      reference: "TR-220",
      note: "Moved into the cold room",
    }),
    movement(now, 40, {
      type: "adjust",
      wineId: "w-cab",
      locationId: "oak",
      bottles: -1 * 12,
      reference: "CNT-104",
      note: "Broken case on the dock",
    }),
    movement(now, 48, {
      type: "receive",
      wineId: "w-wv-pinot",
      locationId: "oak",
      bottles: 12 * 12,
      reference: "PO-4472",
    }),
    movement(now, 55, {
      type: "ship",
      wineId: "w-st-emilion",
      locationId: "oak",
      bottles: 2 * 12,
      reference: "INV-9114",
      account: "Hill & Rye",
    }),
    movement(now, 70, {
      type: "allocate",
      wineId: "w-st-emilion",
      locationId: "oak",
      bottles: 6 * 12,
      reference: "HOLD-331",
      account: "Valley Provisions",
    }),
    movement(now, 80, {
      type: "receive",
      wineId: "w-reserva",
      locationId: "oak",
      bottles: 12 * 12,
      reference: "PO-4466",
    }),
    movement(now, 90, {
      type: "ship",
      wineId: "w-rose",
      locationId: "oak",
      bottles: 6 * 12,
      reference: "INV-9120",
      account: "Osteria Mare",
    }),
    movement(now, 100, {
      type: "release",
      wineId: "w-charmes",
      locationId: "oak",
      bottles: 2 * 12,
      reference: "HOLD-318",
      account: "Chez Lumen",
      note: "Account cut the November list",
    }),
    movement(now, 120, {
      type: "receive",
      wineId: "w-bdb",
      locationId: "oak",
      bottles: 4 * 6,
      reference: "PO-4458",
    }),
    movement(now, 130, {
      type: "ship",
      wineId: "w-barolo",
      locationId: "oak",
      bottles: 1 * 12,
      reference: "INV-9126",
      account: "The Copper Spoon",
    }),
    movement(now, 140, {
      type: "adjust",
      wineId: "w-tawny",
      locationId: "oak",
      bottles: -2,
      reference: "CNT-101",
      note: "Staff tasting",
    }),
    movement(now, 150, {
      type: "transfer",
      wineId: "w-cab",
      locationId: "oak",
      toLocationId: "sf",
      bottles: 1 * 12,
      reference: "TR-214",
      note: "Will-call for a pickup",
    }),
  ]

  return { wines, locations, stock, movements }
}
